import type {Metadata} from 'next'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import LegalDocument from '@/components/legal/LegalDocument'

export const metadata: Metadata = {
    title: 'Termos de Uso | Maskot Edu',
    description: 'Termos e Condições de Uso da Plataforma Maskot Edu.',
}

export default function TermsPage() {
    return (
        <>
            <Header/>
            <LegalDocument title="Termos e Condições de Uso da Plataforma Maskot Edu" lastUpdated="07 de Março de 2026">
                <p>
                    Estes Termos de Uso e Condições Gerais regulam o acesso, o cadastro e a utilização dos serviços e da plataforma Maskot Edu, disponibilizada pela Maskot EDU CRM Educacional, sociedade empresária limitada, regularmente inscrita no CNPJ/ME sob o nº 55.188.948/0001-04., com sede na Rua Propriá, 413, Centro, Aracaju-SE.
                </p>
                <p>
                    Ao assinar eletronicamente, realizar o cadastro, efetuar login pela primeira vez ou utilizar de qualquer forma as funcionalidades da Plataforma, a instituição contratante e seus respectivos usuários autorizados declaram que leram, compreenderam e aceitaram integralmente e sem ressalvas este documento, bem como a Política de Privacidade e eventuais Acordos de Tratamento de Dados Pessoais (DPA) aplicáveis.
                </p>

                <h2>1. Do Aceite e da Validade da Assinatura Eletrônica</h2>
                <p><strong>1.1. Capacidade de Representação:</strong> O usuário que realizar o aceite destes Termos em nome da Escola declara e garante, sob as penas da lei, que possui plenos poderes legais, estatutários ou contratuais para vincular a referida instituição a este instrumento e assumir obrigações financeiras e legais.</p>
                <p><strong>1.2. Validade Eletrônica:</strong> As Partes reconhecem, de comum acordo, a validade, a eficácia e a força executiva atinente ao aceite concedido por meios eletrônicos (como o clique na caixa de seleção inteligente &quot;Li e Aceito&quot;, o início do fluxo de pagamento financeiro, ou o primeiro acesso via login/senha e tokens), nos exatos termos do art. 10, § 2º, da Medida Provisória nº 2.200-2/2001 e disposições pertinentes da Lei nº 14.063/2020.</p>
                <p><strong>1.3. Registro de Auditoria (Logs):</strong> O aceite e o consentimento registrados de forma eletrônica constarão dos bancos de dados e trilhas de auditoria da Maskot, contendo rastros idôneos de vinculação da Escola, tais como, no mínimo: endereço IP de origem, data e hora cronológica da ação, identificador de dispositivo (user-agent) e a versão vinculada destes Termos.</p>

                <h2>2. Objeto da Plataforma e Disponibilização do Serviço</h2>
                <p><strong>2.1. Escopo de Uso:</strong> A Maskot Edu constitui uma solução tecnológica abrangente fornecida na modalidade SaaS (Software as a Service, ou software como serviço), concebida para a otimização da gestão educacional e das rotinas integradas de relacionamento com o cliente. Entre os recursos da Plataforma, destacam-se: (a) CRM educacional, governança sobre a jornada de captação de leads, alunos e responsáveis; (b) ferramentas de agendamento e a disponibilização de formulários de captação abertos ao público; (c) canais de comunicação multicanal (e-mail, WhatsApp etc.); (d) programação de fluxos de automação, réguas de relacionamento (campanhas) integrados com relatórios analíticos (analytics) de desempenho, permitindo importações/exportações; (e) gestão administrativa de usuários, controle granular de perfis de acesso, e manutenção de logs de segurança; (f) funcionalidades pautadas em Inteligência Artificial e (g) conectividade com serviços externos.</p>
                <p><strong>2.2. &quot;Como Está&quot; (As Is):</strong> O Direito de uso da Plataforma é fornecido fundamentalmente e estritamente no estado em que a tecnologia se encontra (&quot;as is&quot;), de forma temporária e não customizada, de modo que a Maskot empreende esforços contínuos de desenvolvimento de melhorias, podendo realizar atualizações periódicas que alterem a composição visual (layout) ou fluxos de usabilidade sistêmica, sem que isso confira à Escola prerrogativas de manutenção regressiva de versões ou de impedir inovações do sistema que porventura retirem funcionalidades subutilizadas pela base geral de clientes, preservando-se todavia o escopo essencial da contratação.</p>

                <h2>3. Gestão de Contas, Cadastro e Credenciais de Segurança</h2>
                <p><strong>3.1. Uso Pessoal e Restrito:</strong> O direito de credenciamento à Plataforma é limitado ao número de acessos/usuários autorizados nominalmente e atrelados ao plano da Escola. A conta, incluindo seus dados de acesso (login e senha), chaves de API, e autenticações vinculadas, é de uso exclusivamente pessoal para cada membro, e não poderá, sob qualquer alegação, ser alienada, transferida ou franqueada de forma combinada (&quot;conta guarda-chuva&quot;) entre múltiplos operadores físicos diferentes.</p>
                <p><strong>3.2. Responsabilidade Integral da Escola:</strong> A Escola assume inteira, irrestrita e exclusiva responsabilidade por quaisquer e todas as atividades perpetradas, inserções oriundas, ou dados transmitidos através das contas associadas ao seu ambiente (tenant/workspace) contratado, assim como detém a responsabilidade pela configuração de senhas robustas pelos seus próprios colaboradores, responsabilizando-se pelo dever da guarda e manutenção do dever de sigilo incondicional sobre as credenciais por parte final do titular direto do perfil.</p>
                <p><strong>3.3. Medidas de Proteção e Resposta a Incidentes:</strong> É dever imperioso que a Escola notifique a Maskot de imediato se identificar qualquer desconfiança plausível de acesso não autorizado, quebra pontual de credencial de algum funcionário, ou falha grave de segurança que possa comprometer a integridade de dados do banco da Escola ou a estabilidade da própria infraestrutura Maskot Edu compartilhado. Mediante solicitação, a Maskot apoiará com as investigações preliminares do log, podendo também, caso sinta que a sua própria rede está ameaçada (ataques massivos, tentativas de força bruta etc), realizar bloqueios precários visando a preservação macro e inabilitar proativamente o foco de incidente. Complementarmente, a Maskot recomenda fortemente o uso de sistemas avançados disponíveis no serviço (onde aplicáveis) em seus acessos críticos (por ex., uso de autenticador em dois fatores/2FA).</p>

                <h2>4. Licenciamento, Restrições e Limites do Uso Tolerável</h2>
                <p><strong>4.1. Concessão de Licença:</strong> Pelo período correspondente à estrita vigência temporal do plano contratado associado e com os recebimentos adimplentes perante a Maskot, é outorgada à Escola uma licença singular de utilização pontual sobre a plataforma intelectual referenciada, compreendendo uma outorga detentora de caráter limitado, intransferível, restrito, não exclusivo e insuscetível a subordinação.</p>
                <p><strong>4.2. Práticas Extremamente Vedadas:</strong> Exige-se o uso regular e lícito do serviço da Maskot Edu, constituindo flagrante descumprimento material por parte da Escola que acarretará penalizações (incluindo eventual interrupção e rompimento forçado) caso esta, diretamente ou via mandatários, cometa as seguintes práticas: (a) copiar parcial ou materialmente, revender, intermediar em benefício concorrencial a terceiros, ou mesmo comercializar o direito sublicenciado de uso intrínseco aos módulos em vigor sem possuir programa firmado e específico de parceiro comercial da própria plataforma (White label/Agency); (b) proceder por descompilação ou valer-se de práticas de engenharia reversa sobre aplicações distribuídas; buscar derivar arquitetura ou códigos fechados da Plataforma; (c) utilizar de recursos agressivos computacionais automáticos imoderados do tipo scripts de navegação (crawlers, robôs não documentados, scrapers) visando manipular interfaces para ganho de dados massivo em detrimento a APIs oficiais e ao consentimento técnico da Maskot Edu.</p>

                <h2>5. Propriedade Intelectual</h2>
                <p><strong>5.1. Acervo Intangível:</strong> A totalidade pertinente dos elementos relativos e atrelados aos serviços, incluídos – não se restringindo – aos elementos visuais, lógicas de algoritmo subjacentes do software, domínios eletrônicos da aplicação base, documentação da interface de acesso, símbolos do design e marca (logomarca Maskot™) formam a única e intocável propriedade intelectual integral da Maskot. A subscrição à Plataforma repassa zero fração atinente da propriedade intangível para a Escola.</p>
                <p><strong>5.2. Dados Cadastrais Escolares e Respeito Titular:</strong> No exato polo oposto, reconhece-se o direito originário perante a massa bruta de informações cadastrais e dados operacionais injetados e captados pelos formulários associados, confirmando a Escola (e indiretamente os alunos/pessoas singulares que o formam) na inconteste exclusividade integral do direito de posse sobre referidos dados base que operem unicamente encapsulados à base relacional atinente ao seu contrato escolar privado.</p>
                <p><strong>5.3. Cessão Irrevogável de Feedback:</strong> Manifestações técnicas, correções reportadas voluntariamente como ideias ou recomendações de aprimoramentos orgânicos prestados à equipe pela Escola podem, livre e integralmente ser processadas e implementadas evolutivamente nas matrizes futuras de serviços gerados pela Maskot Edu para seus entes gerais de mercado, as quais não configurarão reconhecimento retroativo de criação conjunta (coautoria remota) nem implicarão qualquer prerrogativas vinculativas de royalties compensatórios futuros à entidade que emitiu o relato de feedback.</p>

                <h2>6. Modelos de Contratação, Gestão de Assinaturas, Pagamentos e Fidelidade</h2>
                <p><strong>6.1. Planos Vinculativos e Escopo Comercial:</strong> A prestação do serviço da Maskot Edu estrutura-se majoritariamente no formato de licenças modulares por assinatura recorrente (mensal, semestral ou anual). O plano base contratado estabelece as prerrogativas financeiras e limites lógicos da conta (ex. cotas de envio de e-mails, execuções limitadas de fluxos de Inteligência Artificial, e quantidade máxima ativa de contatos/leads paralelos).</p>
                <p><strong>6.2. Assinatura, Renovação Automática e Meios de Pagamento:</strong> A contratação formaliza-se com o primeiro pagamento compensado. Visando a conveniência e a não interrupção sistêmica do CRM, as assinaturas (independentemente de sua periodicidade) presumem-se de renovação sucessiva e automática aos termos de seus ciclos. As compensações processam-se majoritariamente por intermédio de gateways homologados (ex: Stripe), recaindo sobre cartão de crédito cadastrado da Escola, repasses atrelados ao PIX ou boletos bancários, quando expressamente disponibilizados nas opções comerciais no ato da aquisição.</p>
                <p><strong>6.3. Upgrades, Downgrades e Franquias Excedentes (Add-ons):</strong> O atingimento estrito aos tetos dos limites atinentes ao seu plano provocará notificações informativas no painel. A Escola poderá, a qualquer tempo, efetuar a ampliação para patamares superiores (Upgrades), com o imediato recálculo pró-rata transacional dos referidos valores atrelados às faturas futuras. Limitações excedentes poderão também ser sanadas emergencialmente habilitando pacotes avulsos e adicionais de repasses modulares (Add-ons). O rebaixamento dos planos (Downgrade) incide estritamente ao final do ciclo contratado em vigência, nunca gerando o estorno retroativo do montante originário proporcional outrora repassado.</p>
                <p><strong>6.4. Política de Desconto atrelada à Contratação com Fidelidade Temporária:</strong> A critério de políticas promocionais e incentivos atrelados à venda, a Maskot poderá ofertar planos de média ou longa duração (como ciclos Anuais) imersos em significativas reduções percentuais comparados às licenças cobradas mensalmente na tabela base. Ao aderir conscientemente com usufruto deste subsídio comercial atrelado, a Escola obriga-se voluntária e expressamente a respeitar a cláusula da garantia temporal mínima (Fidelidade), em regra de 12 (doze) meses contínuos. A rescisão antecipada imotivada pela contratante nestes enquadramentos subsidiados impõe na apuração imediata, em prol da Maskot, de multa resolutória e equitativa fixada em montante compensatório equivalente (ex: recolhimento dos descontos das mensalidades já percorridas ou a cobrança de um percentual fixo sobre as parcelas vincendas, conforme propostas das vendas), com base lícita e amparada legalmente para a finalidade de restabelecimento do equilíbrio financeiro original não adimplido.</p>
                <p><strong>6.5. Morosidade Financeira e Suspensão Contínua:</strong> A detecção fundamentada e a confirmação sistemática decorrente de recusas perante operadoras de crédito, atreladas à ausência do pagamento no vencimento aprazado, estabelece sumariamente o estado irrefutável de mora. É passível a aplicação de multas moratórias de 2% (dois por cento) e juros de mora em limites legais estabelecidos de 1% (um por cento) ao mês pro rata die sobre o saldo em aberto. O atraso continuado perante o vencimento natural gera bloqueio restritivo imediato nos acessos sistêmicos do painel. Decorrido um prazo estipulado de inadimplemento superior contínuo e sem regularização após alertas razoáveis, viabiliza-se unilateralmente a paralisação completa final e a rescisão do contrato com as perdas dos dados na infraestrutura operada perante a conta devedora.</p>

                <h2>7. Tratamento Legal de Dados (Foco na LGPD e Suboperação)</h2>
                <p><strong>7.1. Separação Estrita de Responsabilidade Perante a LGPD:</strong> O alicerce fundamental acerca das delimitações perante o diploma legislativo consubstanciado na Lei n.º 13.709/2018 (Lei Geral de Proteção de Dados - “LGPD”) estabelece que a figura jurídica empossada no papel formal decisório como a Controladora sobre as diretrizes, natureza finalística e a razão para o armazenamento ativo (ou inativo) inerente, relativas às bases massivas atinentes dos dados individuais de alunos, educadores, capturas sensíveis e/ou pais injetadas organicamente é essencialmente e de modo irrefutável exclusiva da Escola usuária. Já a Maskot, como elo facilitador que propicia a salvaguarda sob diretrizes, atuará na limitação rígida das ações meramente figuradas correspondentes às obrigações do pilar tipificado pela Lei como a Operadora.</p>
                <p><strong>7.2. Indispensabilidade Lícita:</strong> Fica desde logo atestado mediante dever formal perante esta subscrição que todas as bases contendo remessas importadas ao painel CRM, em especial endereços telefônicos e registros para envio contínuo foram angariadas e mantidas integralmente e a qualquer tempo com forte sustentáculo que evidencie manifestação livre (consentimento expresso passível sob prova documental) ou demais pressupostos idôneos baseados imperiosamente em obrigações de legitimo interesse escolar devidamente ponderado na origem coletora (Escola) face ao lead captado perante a Plataforma, a fim de expurgar sobre o papel estritamente executor e neutro da Maskot quaisquer sanções que porventura reflitam um cenário derivado da inclusão clandestina (aquisições irregulares) proveniente diretamente dos esforços primários que envolvam uma irregularidade contundente promovida isoladamente pela contratante originária. Tendo ressalvada, em caso específico com foco pontual de uso perante solicitações emitidas pelos próprios representantes físicos titulares finais que invoquem retificação ou seu &quot;Direito Absoluto a Transparência, Bloqueio ou Eliminação&quot;, a ciência da Maskot deverá encaminhar ou orientar tecnicamente visando transparecer como única via do titular a persecução e a finalização pelo canal próprio do corpo do encarregado apontado do ente Controlador em linha direita.</p>
                <p><strong>7.3. Suboperadores Consentidos e Infraestrutura Segregada:</strong> Ao validar os presentes Termos a Escola, no papel natural de parte Controladora, endossa previamente uma anuência sistêmica perante o papel da Maskot a promover o subestabelecimento tecnológico operacional (concessão a Suboperadores) das frações limitadas perante fornecimentos prestados perante elos externos formados por gigantes sistêmicas reconhecidas sobre o provedor do serviço de hospedagem atrelada – e infraestrutura física escalável, usualmente em modalidade remota (Corporate Cloud computing), ciente das possíveis ocorrências necessárias estipuladas visando o uso de datacenters geolocalizados remotamente perante bases atestadas em &quot;Transferências Internacionais de Dados&quot; regradas pelas garantias razoavelmente esperadas.</p>

                <h2>8. Aspectos Particulares: Mensageria Interativa Externa e WhatsApp</h2>
                <p><strong>8.1. Propriedade sobre Conteúdo Despachado:</strong> Todas as premissas contundentes sobre os reflexos textuais emitidos de fato aos alvos cadastrais englobam-se perante e isoladamente como encargo unilateral vinculante em matéria passiva da própria Escola (e de todas suas campanhas deflagradas ativamente através do roteamento da Plataforma Edu para fora das limitações perante provedores de terceiros).</p>
                <p><strong>8.2. Prerrogativas Anti-Spam Rigorosas e Independência sobre Bloqueios em Trânsito (Termos Meta):</strong> Os reflexos originários englobam atestados em evitar fluxos maciços repetitivos não esperados e vedam abusividade contumaz na frequência irregular perante desrespeito de mecanismos essenciais obrigatórios em optar por evadir ou ser sumariamente descartado (Respeito inquestionável a requisições definitivas via comando automatizado tipo de encerramento, Unsubscribe/Opt-Out). Com particular detaque envolvendo mensageria interligada em ecossistema direto oficial a WhatsApp API, a Maskot ratifica cabal conhecimento compartilhado que tal integração obrigatoriamente vincula a Escola aos &quot;Termos Comerciais&quot; rígidos estabelecidos pontualmente nas políticas soberanas internas impostas unilateralmente pela provedora final (Meta Platforms Inc). Consequentemente, a Maskot se isenta radical, categórica e irrenunciavelmente diante da Escola que caso venha a recair em possíveis eventos de degradações reputacional originada por baixo índice qualitativo originados em campanhas imoderadas do CRM, suspensão ou sanções extremas tipo banimentos radicais ao número virtual do titular que reflitam desdobramentos efetuados ativamente proveniente por auditores do WhatsApp, os resultados negativos atinentes não poderão repercutir na responsabilização mútua com o arcabouço provido dentro das ferramentas em si distribuída sobre o Maskot Edu, que constitui instrumento meramente facilitador sem escrutínio moderador perante e posterior aos disparos de conversões emitidos.</p>

                <h2>9. Limites Relativos do Motor pautado em Inteligência Artificial</h2>
                <p><strong>9.1. Transparência da Natureza Assistiva e Probabilidade Tecnológica:</strong> A Plataforma conjuga recursos subadjacentes avançados suportados em Modelos de Linguagem de Grande Escala operados remotamente e cedidos através de componentes tecnológicos terceirizados atrelados diretamente nas funções proativas inerentes as engrenagens da Maskot (motores IA como os modelos da LLM API p. exemplo Google Gemini – que processarão requisições, textos interpretáveis dos leads e resumirão conteúdos de respostas automáticas perante a instrução original). A tecnologia em suma carrega a advertência inequívoca perante as entidades operadoras cientes das manifestações e resultados advindos formados na raiz tecnológica assentada essencialmente no modelo em &quot;previsões atreladas a campos intrinsecamente e substanciales probabilísticos&quot;, cujo preceitos apontam para a tolerável propensão natural estatística de ocorrências com devoluções geradas ocasionando informações distorcidas temporariamente apelidadas (&quot;Alucinações Tecnológicas&quot;).</p>
                <p><strong>9.2. Condição Exclusiva a Validação e Supervisão por Elemento Humano:</strong> Toda devolutiva em tese configurando em sugestões da premissa IA ou propostas automatizadas baseadas pela engrenagem sistêmica Maskot para tratativa dos leads operam unicamente como um suporte meramente assistencial suplementar, e de uso restrito referenciado com fim na minimização primária perante atividades repetitivas na captação inicial orgânica, recaindo incontestemente na obrigação definitiva sobre à avaliação discricionária dos coordenadores e operadores reais escalados pertencentes inerentes ao grupo associado das escolas vinculativas à responsabilidade definitiva a validar rigorosa procedência em respostas proativas em seu papel final, sobressaem no isento da eventual vinculação perante promessas irreais firmadas autonomamente originárias aos consumidores/pais de concessões irrazoáveis oriundas por ventura advinda de processadores virtuais (ex. Concessão indevida e atípica sistêmica p/ um suposto desconto). A parametrização adequada, incluindo treinamento pontual formatado nos comandos de diretrizes centrais nas caixas (System prompts), também consubstancia a integridade final sob condução contínua e aprimorada de responsabilidade sobre a Escola e respectivo acompanhamento operacional.</p>

                <h2>10. Limitação e Segregação de Responsabilidade Civil (Indenizações Mitigadas)</h2>
                <p><strong>10.1. Teto Base de Responsabilização Consolidado (&quot;Liability Cap&quot;):</strong> Salvo nos casos onde seja vetado perante norma expressa obrigacionária pública de caráter ilimitado, define-se que na máxima extensão interpretativa e validada garantida pelos ditames dos institutos legislativas permitida pela legislação do país regente, eventual imputabilidade e procedência a ser admitida de ordem subsidiada reparatória perante desavenças civis e financeiras consolidadas onde, comprovada estritamente e cabalmente mediante julgado transitivo em trâmite legal de danos que incorram da culpa imperícia manifesta (direta decorrente pelo serviço/Plataforma Maskot) que causaram perdas comprovadas quantificáveis limitam total e inexoravelmente, não ultrapassar – de maneira em aglomerados isolados ou globais processuais ao valor global idêntico limitante ao montante total consolidado atrelado e apoderado (valores estritos repassados devidamente liquidados em favor perante a subscrição pelo plano) desembolsada formalmente através da respectiva &quot;Contratante Escolar Lesada&quot;, unicamente perante faturas apuradas do sistema atreladas durante o prazo compreendido nos 12 (doze) últimos meses imediatos pretéritos que se antecedem como contagem retroativa à data fixada ao fato gerador motivador consolidado impulsionante do dano acionado discutido na queixa civil/inépcia.</p>
                <p><strong>10.2. Cláusula de Isenção Abrangente de Perdas e Danos Abstratos (Danos Indiretos e Cessantes):</strong> A Maskot perante as restrições naturais perante provimento compartilhado e de complexidade contínua interligada de forma indubitável exime-se perante obrigatoriedade sobre eventuais ocorrências pleiteadas sobre projeções em reparação atinentes sobre as consequências de falhas não dolosas atestadas, englobando sem se sujeitar unicamente as: exclusões categoricamente aos dispêndios hipotéticos relativos aos (&quot;lucros frustrados/cessantes&quot;) gerados após ocorrências não computáveis sobre perda em base quantificada decorrente acidental das interrupções, ou demandas isoladas punitivas, perda de &quot;chance&quot; com captação interligada, e de quaisquer abalo abstrato material indireto ou colateral provindos por fatores sistêmicos correlatos da instabilidade esporádica intrínseca da natureza digital vinculantes aos serviços da Maskot.</p>
                <p><strong>10.3. Cláusula Indenizatória Perante Terceiros Intervenientes – “Obrigação Originária da Contratante (Hold Harmless)”:</strong> Conselhos pautados de quebra de diretrizes ou violações expressas de regulamentos governamentais acarretados sobre mal uso, submetem a Escola à proteção blindada contundente do pólo passivo onde recair contra Maskot e suas operadoras/diretorias ligadas corporativamente que envolvam defesas forçadas em trâmites abertos propostos a juízo promovidos na origem e advindo como queixa manifesta pleiteada por agentes públicos restritos, sanções de fiscais governamentais limitantes de agências (Multas da Autoridade de Proteção - &quot;ANPD&quot;), representações advindas originárias mediante órgãos consumidores de defesas aos pais (ex: Procons), acionadas na dependência direta estritamente enquadradas pela quebra e não aderência perante regras atinentes as &quot;Práticas e Deveres desta Cláusula Contratual Originárias Promovidas Pela Escola&quot; na utilização dos dados inseridos/coletadas ilicitamente ou uso discriminatório dos artefatos promovidos, de tal forma incumbirá em obrigação final restrita que as apurações, atuações processuais de defesa ativa de mérito e perdas indenizatórias decorrentes destas desavenças finais propostas em instâncias perante a Maskot sejam arcadas sem pestanejar (e as perdas em liquidez da parte demandada restituídas ou custeadas diretamente à vista com juros legais correntes) pelo montante e despesas consolidadas mediante dever obrigatório atestada pela matriz de responsabilidade exclusiva sobre a geradora principal finalística, a Escola interveniente do plano subscrito inicial originário deflagrador na situação do fato concreto. O alicerce desta obrigação restabelece perante a limitação do ambiente em isentar qualquer responsabilidade da parceira originária no serviço Maskot Edu.</p>

                <h2>11. Disponibilidade, Parametrização dos Relatórios e Eventuais Falhas Originadas Pelo Provedor</h2>
                <p><strong>11.1. Garantias Temporais Esforçadas não Fim:</strong> Não subsistindo atestações formais individualizadas em Acordo Expresso Apartado Sobre Garantias Finais Nível Atendimento (Agreement-SLA obrigatório de Resultado). A Maskot balizada por padrões internacionais de esforço no zelo técnico sobre nuvem empreenderá meios necessários continuados razoáveis de caráter pautado para uma estabilidade técnica ininterrupta; desvencilhando perante as inviabilidades corriqueiras causadas por força maior como, indisponibilidade transitória programadas decorrentes na rede de janelas e manutenções ou intempéries causadas originárias alocadas na ponta remanescente das concessionárias na internet pública ou limitações técnicas na origens de conectividade entre Aplicações e APIs base originarias de rotas fechadas perante seus serviços de integrações dependentes fornecidos na estrutura isolada (Ex. Mudanças críticas e drásticas nas rotas programadas dos subcomponentes de faturamento operados externamente e roteamentos via empresas independentes mensageiras não abarcadas no domínio da Maskot Edu).</p>

                <h2>12. Retenção Transitória e Obrigatoriedade da Extinção Efetiva perante Destituição</h2>
                <p><strong>12.1. Prazo Rescisório, Liberação Temporizada em Processo a Portabilidade Restrita:</strong> Confeccionando a declaração explícita atinente mediante finalização irreversível (rescisão operada efetivada), decorrida das vontades paritárias mútuas nas regras estipuladas ao prazo não prorrogado aprazado natural de comunicação aviso restrito de validade dos Planos Contratados encerra-se e delimita-se à Escola os acessos vinculares irrestritos. Fixa-se período transicional garantido em no máximo contíguo estipulado de 90 dias corridos para proceder e executar de forma orgânica à exportação consolidada massiva perante planilhas em interfaces exportadoras abertas pela Plataforma inerentes os registros analíticos, quadros das listagens CRM e afins em log operacionais inseridos perante propriedade imutável restrita no artigo dos titulares garantida.</p>
                <p><strong>12.2. Expurgo Imutável das Base Ativas Operacionais:</strong> Posterior consumação imposta atrelada com rigor originária à prescrição ao prazo restrito de carência delimitado superior estabelecido, consolida-se permissão irrestrita atinente na conformidade legal à restrição procedida perante destruição/eliminação restrita lógica operada dos banco dados ativos expostos em acessos remotos das nuvens isoladas ao ambiente e instâncias produtivas operacionais da infraestrutura central atinente exclusivas à Escola; resvalada restritamente e legalizado o dever retentivo obrigatório perante os backups apartados de dados operacionais que subsistirão excepcionais guardados congelados pelo período em limite da expiração unicamente necessária ao uso legítimo defensiva processuais na conformidade na LGPD na estipulada obrigatoriedade sobre bases em guarda de log preservativos perante disposições em lei p/ exercício legal temporal regular obrigatório ou obrigações contratuais restritivas.</p>

                <h2>13. Vigência e Atualizações Contratuais Constantes Progressivas</h2>
                <p>A versão formal ora atestada no preâmbulo poderá eventualmente e sem prejuízo natural mediante avanços inerentes as interações jurídicas normais ou desdobramentos atrelados perante o crescimento escalável macro no escopo atrelado perante novos atributos originar perante Maskot modificações com revisão das cláusulas vigentes consolidadas pautas deste instrumento atualizado periodicamente. O fluxo sobre alterações drásticas, reajustes substanciais restritivos que porventura cerceiam liberdades em vigências atuais atestadas nas contas, seguirão acompanhados em comunicação eletrônica (ex: e-mail institucional atrelado do admin. cadastrado no perfil escolar), antecedendo na conformidade razoável (preferencial perante 15 ou 30 dias na antecipação restritiva aplicável). Ratificada atestação de não-oposição declarada associada integralmente continuada com acesso orgânico sistemáticos supervenientes mediante o painel superados prazos propostos fixaram atestado inequívoco atrelado tático em prosseguir com eficácia a irrevogável sobre a integralização validada à luz do escopo revisado.</p>

                <h2>14. Foro e Escolha Predominante da Disposição Lei da Normativa Referencial</h2>
                <p>A estipulada materialidade declaratória intrínseca, deveres procedimentais interligadas perante estes preceitos atestarão interpretativas e sujeitas as ordenanças imperiosas proveniente unicamente nos parâmetros normativos atinentes e ordenamento das Leis regentes da República Federativa do Brasil. Atribui-se aos parâmetros delimitadores litígios, a não remissão e indicação única prelativa exclusiva correspondente estipulados restrito à propositura p/ demandas nas vias restritas perante ao Fórum na comarca principal da sede oficial originárias apontados atinentes aos quadros na Maskot correspondentes fixados em Aracaju-SE, por força cabal na eleição declinada com a efetividade mútua no resguardo renunciando na prerrogativas e excepcionalidade p/ foro distintos originários no limite territorial das partes contendoras independente estipulação p/ eventuais abrandamentos garantidos excepcionadas e abstenções a instâncias diferenciadamente mais qualificadas na territorialidade diversa ao eleito isolado e exato desta cláusula principal limitante base preeminente nas diretrizes procedimentais judiciais estritas.</p>

                <hr style={{ margin: '2rem 0', borderColor: 'var(--border)' }} />
                
                <h2>Contatos Institucionais e Governança Perante Obrigatoriedades Pautadas na LGPD</h2>
                <p>Comunicações em questionamentos interligados restritamente, dúvidas analíticas procedimentais e o encaminhamento pautado sobre questionamentos p/ solicitações em caráter fundamentados com finalidade específica em cumprimento a resoluções na privacidade baseadas em tratamento referenciados por normativos do Marco Legal do Tratamentos sobre Privacidade do Ambiente Eletrônicos poderão ser direcionados/demandadas nos trâmites diretamente direcionadas à alçada de atuação em supervisão de Proteções aos Dados Atrelados sob escopo e do nosso Encarregado apontado (DPO interno operantes em dados pessoais) mediante as requisições atreladas nos canais oficiais através do e-mail: <a href="mailto:juridico@maskotedu.com.br">juridico@maskotedu.com.br</a>.</p>
            </LegalDocument>
            <Footer/>
        </>
    )
}