// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogPostDocumentDataSlicesSlice =
  | BannerAdSlice
  | RichTextSlice
  | CalloutSlice
  | ContentTableSlice
  | QuoteSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Excerpt field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Categoria field in *Blog Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Gestão Escolar
   * - **API ID Path**: blog_post.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    | "Gestão Escolar"
    | "Marketing"
    | "Retenção"
    | "Tecnologia"
    | "Vendas"
    | "Gestão de Leads"
    | "Leads"
    | "Retenção de Matrículas"
    | "Funil de Matrículas",
    "filled"
  >;

  /**
   * Autor field in *Blog Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Content for Autor documents
 */
interface AuthorDocumentData {
  /**
   * Nome field in *Autor*
   *
   * - **Field Type**: Text
   * - **API ID Path**: author.name
   */
  name: prismic.KeyTextField;

  /**
   * Foto field in *Autor*
   *
   * - **Field Type**: Image
   * - **API ID Path**: author.photo
   */
  photo: prismic.ImageField<never>;

  /**
   * Cargo field in *Autor*
   *
   * - **Field Type**: Text
   * - **API ID Path**: author.role
   */
  role: prismic.KeyTextField;

  /**
   * Bio field in *Autor*
   *
   * - **Field Type**: Rich Text
   * - **API ID Path**: author.bio
   */
  bio: prismic.RichTextField;

  /**
   * LinkedIn field in *Autor*
   *
   * - **Field Type**: Link
   * - **API ID Path**: author.linkedin
   */
  linkedin: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Instagram field in *Autor*
   *
   * - **Field Type**: Link
   * - **API ID Path**: author.instagram
   */
  instagram: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Autor document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

/**
 * Content for Blog Settings documents
 */
interface BlogSettingsDocumentData {
  /**
   * Sidebar Banner Image field in *Blog Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_settings.sidebar_banner_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  sidebar_banner_image: prismic.ImageField<never>;

  /**
   * Sidebar Banner Link field in *Blog Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_settings.sidebar_banner_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  sidebar_banner_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Blog Settings document from Prismic
 *
 * - **API ID**: `blog_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogSettingsDocumentData>,
    "blog_settings",
    Lang
  >;

export type AllDocumentTypes =
  | AuthorDocument
  | BlogPostDocument
  | BlogSettingsDocument;

/**
 * Primary content in *BannerAd → Default → Primary*
 */
export interface BannerAdSliceDefaultPrimary {
  /**
   * Image field in *BannerAd → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_ad.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *BannerAd → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_ad.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * CTA Text field in *BannerAd → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: Conheça o Maskot Edu →
   * - **API ID Path**: banner_ad.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;
}

/**
 * Default variation for BannerAd Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerAdSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerAdSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BannerAd*
 */
type BannerAdSliceVariation = BannerAdSliceDefault;

/**
 * BannerAd Shared Slice
 *
 * - **API ID**: `banner_ad`
 * - **Description**: BannerAd
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerAdSlice = prismic.SharedSlice<
  "banner_ad",
  BannerAdSliceVariation
>;

/**
 * Primary content in *ContentTable → Default → Primary*
 */
export interface ContentTableSliceDefaultPrimary {
  /**
   * title field in *ContentTable → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_table.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * col1_header field in *ContentTable → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_table.default.primary.col1_header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  col1_header: prismic.KeyTextField;

  /**
   * col2_header field in *ContentTable → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_table.default.primary.col2_header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  col2_header: prismic.KeyTextField;

  /**
   * col3_header field in *ContentTable → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_table.default.primary.col3_header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  col3_header: prismic.KeyTextField;

  /**
   * col4_header field in *ContentTable → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_table.default.primary.col4_header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  col4_header: prismic.KeyTextField;
}

/**
 * Primary content in *ContentTable → Default → Items*
 */
export interface ContentTableSliceDefaultItem {
  /**
   * cell_1 field in *ContentTable → Default → Items*
   *
   * - **Field Type**: Text
   * - **API ID Path**: content_table.default.items[].cell_1
   */
  cell_1: prismic.KeyTextField;

  /**
   * cell_2 field in *ContentTable → Default → Items*
   *
   * - **Field Type**: Text
   * - **API ID Path**: content_table.default.items[].cell_2
   */
  cell_2: prismic.KeyTextField;

  /**
   * cell_3 field in *ContentTable → Default → Items*
   *
   * - **Field Type**: Text
   * - **API ID Path**: content_table.default.items[].cell_3
   */
  cell_3: prismic.KeyTextField;

  /**
   * cell_4 field in *ContentTable → Default → Items*
   *
   * - **Field Type**: Text
   * - **API ID Path**: content_table.default.items[].cell_4
   */
  cell_4: prismic.KeyTextField;
}

/**
 * Default variation for ContentTable Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentTableSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentTableSliceDefaultPrimary>,
  Simplify<ContentTableSliceDefaultItem>
>;

/**
 * Slice variation for *ContentTable*
 */
type ContentTableSliceVariation = ContentTableSliceDefault;

/**
 * ContentTable Shared Slice
 *
 * - **API ID**: `content_table`
 * - **Description**: ContentTable
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentTableSlice = prismic.SharedSlice<
  "content_table",
  ContentTableSliceVariation
>;

/**
 * Primary content in *Callout → Default → Primary*
 */
export interface CalloutSliceDefaultPrimary {
  /**
   * Tipo field in *Callout → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Default Value**: Dica
   * - **API ID Path**: callout.default.primary.variant
   */
  variant: prismic.SelectField<"Dica" | "Informação" | "Atenção" | "Sucesso", "filled">;

  /**
   * Título field in *Callout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **API ID Path**: callout.default.primary.title
   */
  title: prismic.KeyTextField;

  /**
   * Conteúdo field in *Callout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **API ID Path**: callout.default.primary.content
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Callout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CalloutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalloutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Callout*
 */
type CalloutSliceVariation = CalloutSliceDefault;

/**
 * Callout Shared Slice
 *
 * - **API ID**: `callout`
 * - **Description**: Callout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CalloutSlice = prismic.SharedSlice<"callout", CalloutSliceVariation>;

/**
 * Primary content in *Quote → Default → Primary*
 */
export interface QuoteSliceDefaultPrimary {
  /**
   * Citação field in *Quote → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **API ID Path**: quote.default.primary.quote
   */
  quote: prismic.RichTextField;

  /**
   * Autor da citação field in *Quote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **API ID Path**: quote.default.primary.author
   */
  author: prismic.KeyTextField;

  /**
   * Cargo / contexto field in *Quote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **API ID Path**: quote.default.primary.role
   */
  role: prismic.KeyTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Texto field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AuthorDocument,
      AuthorDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BlogSettingsDocument,
      BlogSettingsDocumentData,
      AllDocumentTypes,
      BannerAdSlice,
      BannerAdSliceDefaultPrimary,
      BannerAdSliceVariation,
      BannerAdSliceDefault,
      CalloutSlice,
      CalloutSliceDefaultPrimary,
      CalloutSliceVariation,
      CalloutSliceDefault,
      ContentTableSlice,
      ContentTableSliceDefaultPrimary,
      ContentTableSliceDefaultItem,
      ContentTableSliceVariation,
      ContentTableSliceDefault,
      QuoteSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceVariation,
      QuoteSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
